from __future__ import annotations


DEMO_MEMBER_ID = "member-001"
DEMO_WASHER_ID = "washer-001"
DEMO_WASH_STATUS_ID = "wash-status-001"

DEMO_WASHER_CAPACITY_KG = 8.0
DEMO_HOUSEHOLD_SIZE = 2
DEMO_REGION = "서울"
DEMO_CITY = "Seoul"

DEMO_CURRENT_LOAD_KG = 5.2
DEMO_SENSOR_LOAD_KG = 5.2
DEMO_WEIGHT_INCREASE_KG = 1.1

DEMO_HOURS_SINCE_LAST_WASH = 72.0
DEMO_URGENT_CLOTHING_COUNT = 2

DEMO_LOAD_VARIATION_KG = 0.3
DEMO_CYCLE_ELAPSED_MINUTES = 38
DEMO_BASE_CYCLE_MINUTES = 78
DEMO_FINAL_SPIN_RPM = 1000

DEMO_DRY_LAUNDRY_WEIGHT_KG = 5.0
DEMO_HAS_DELICATE_ITEMS = False
DEMO_NEEDS_FAST_DRY = True
DEMO_HAS_OUTDOOR_SPACE = False
DEMO_HAS_DRYER = True
DEMO_ODOR_SENSITIVE = True
DEMO_INDOOR_HUMIDITY = 62
DEMO_INDOOR_TEMPERATURE = 24.0
DEMO_AIRFLOW_LEVEL = 40
DEMO_DEHUMIDIFIER_ON = False
